version: 0.2

env:
  secrets-manager:
    BUILD_SECRETS: "github-secrets:BUILDSECRETS"

phases:
  pre_build:
    commands:
      # Parse the secrets
      - export AWS_ACCOUNT_ID=$(echo $BUILD_SECRETS | jq -r '.AWS_ACCOUNT_ID')
      - export AWS_DEFAULT_REGION=$(echo $BUILD_SECRETS | jq -r '.AWS_DEFAULT_REGION')
      - export IMAGE_REPO_NAME=$(echo $BUILD_SECRETS | jq -r '.IMAGE_REPO_NAME')
      - export IMAGE_TAG=$(echo $BUILD_SECRETS | jq -r '.IMAGE_TAG')
      # ECR login
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG